<?php
// $Id$

/**
 * @file
 * Install file for the pcp module.
 */

/**
 * Implements of hook_schema()
 */
function pcp_schema() {
  $schema['profile_pcp'] = array(
    'description' => 'Stores PCP required profile fields.',
    'fields' => array(
      'fid' => array(
      'type' => 'int',
      'not null' => TRUE,
      'description' => 'Field ID',
      ),
    ),
    'primary key' => array('fid'),
  );

  return $schema;
}